package com.luna.app

import android.graphics.Color
import com.luna.app.R

data class LunaTheme(
    val name: String,
    val displayNameRes: Int,
    val bgPrimary: Int,
    val bgSurface: Int,
    val textPrimary: Int,
    val textSecondary: Int,
    val accent: Int,
    val accentDark: Int,
    val chipBg: Int,
    val chipBgActive: Int,
    val chipText: Int,
    val chipTextActive: Int,
    val sliderTrack: Int,
    val sliderThumb: Int,
    val scrollPadBg: Int,
    val scrollPadThumb: Int,
    val scrollPadTrack: Int,
    val scrollPadArrow: Int,
    val gridBtnBg: String,
    val gridBtnText: String,
    val gridBtnBorder: String,
    val gridBtnActiveBg: String
)

object ThemeManager {
    val themes = listOf(
        LunaTheme(
            name = "oscuro",
            displayNameRes = R.string.theme_dark,
            bgPrimary = Color.parseColor("#0D0D0D"),
            bgSurface = Color.parseColor("#1A1A1A"),
            textPrimary = Color.WHITE,
            textSecondary = Color.parseColor("#AAAAAA"),
            accent = Color.parseColor("#4FC3F7"),
            accentDark = Color.parseColor("#0288D1"),
            chipBg = Color.parseColor("#2A2A2A"),
            chipBgActive = Color.parseColor("#4FC3F7"),
            chipText = Color.parseColor("#AAAAAA"),
            chipTextActive = Color.WHITE,
            sliderTrack = Color.parseColor("#333333"),
            sliderThumb = Color.parseColor("#4FC3F7"),
            scrollPadBg = Color.parseColor("#1A1A1A"),
            scrollPadThumb = Color.parseColor("#4FC3F7"),
            scrollPadTrack = Color.parseColor("#333333"),
            scrollPadArrow = Color.parseColor("#555555"),
            gridBtnBg = "#2A2A2A",
            gridBtnText = "#FFFFFF",
            gridBtnBorder = "#3A3A3A",
            gridBtnActiveBg = "#4FC3F7"
        ),
        LunaTheme(
            name = "claro",
            displayNameRes = R.string.theme_light,
            bgPrimary = Color.parseColor("#F5F5F5"),
            bgSurface = Color.parseColor("#E0E0E0"),
            textPrimary = Color.parseColor("#1A1A1A"),
            textSecondary = Color.parseColor("#666666"),
            accent = Color.parseColor("#0288D1"),
            accentDark = Color.parseColor("#01579B"),
            chipBg = Color.parseColor("#D0D0D0"),
            chipBgActive = Color.parseColor("#0288D1"),
            chipText = Color.parseColor("#666666"),
            chipTextActive = Color.WHITE,
            sliderTrack = Color.parseColor("#BDBDBD"),
            sliderThumb = Color.parseColor("#0288D1"),
            scrollPadBg = Color.parseColor("#E0E0E0"),
            scrollPadThumb = Color.parseColor("#0288D1"),
            scrollPadTrack = Color.parseColor("#BDBDBD"),
            scrollPadArrow = Color.parseColor("#888888"),
            gridBtnBg = "#D0D0D0",
            gridBtnText = "#1A1A1A",
            gridBtnBorder = "#BDBDBD",
            gridBtnActiveBg = "#0288D1"
        ),
        LunaTheme(
            name = "azul_nocturno",
            displayNameRes = R.string.theme_night_blue,
            bgPrimary = Color.parseColor("#0A0E27"),
            bgSurface = Color.parseColor("#141B3D"),
            textPrimary = Color.WHITE,
            textSecondary = Color.parseColor("#8899CC"),
            accent = Color.parseColor("#448AFF"),
            accentDark = Color.parseColor("#2962FF"),
            chipBg = Color.parseColor("#1E2859"),
            chipBgActive = Color.parseColor("#448AFF"),
            chipText = Color.parseColor("#8899CC"),
            chipTextActive = Color.WHITE,
            sliderTrack = Color.parseColor("#1E2859"),
            sliderThumb = Color.parseColor("#448AFF"),
            scrollPadBg = Color.parseColor("#141B3D"),
            scrollPadThumb = Color.parseColor("#448AFF"),
            scrollPadTrack = Color.parseColor("#1E2859"),
            scrollPadArrow = Color.parseColor("#5566AA"),
            gridBtnBg = "#1E2859",
            gridBtnText = "#FFFFFF",
            gridBtnBorder = "#2A3A6A",
            gridBtnActiveBg = "#448AFF"
        ),
        LunaTheme(
            name = "neon_verde",
            displayNameRes = R.string.theme_neon_green,
            bgPrimary = Color.parseColor("#0D1A0D"),
            bgSurface = Color.parseColor("#1A2E1A"),
            textPrimary = Color.WHITE,
            textSecondary = Color.parseColor("#88CC88"),
            accent = Color.parseColor("#00E676"),
            accentDark = Color.parseColor("#00C853"),
            chipBg = Color.parseColor("#1A3A1A"),
            chipBgActive = Color.parseColor("#00E676"),
            chipText = Color.parseColor("#88CC88"),
            chipTextActive = Color.parseColor("#0D1A0D"),
            sliderTrack = Color.parseColor("#1A3A1A"),
            sliderThumb = Color.parseColor("#00E676"),
            scrollPadBg = Color.parseColor("#1A2E1A"),
            scrollPadThumb = Color.parseColor("#00E676"),
            scrollPadTrack = Color.parseColor("#1A3A1A"),
            scrollPadArrow = Color.parseColor("#55AA55"),
            gridBtnBg = "#1A3A1A",
            gridBtnText = "#FFFFFF",
            gridBtnBorder = "#2A5A2A",
            gridBtnActiveBg = "#00E676"
        ),
        LunaTheme(
            name = "magenta",
            displayNameRes = R.string.theme_magenta,
            bgPrimary = Color.parseColor("#1A0D1A"),
            bgSurface = Color.parseColor("#2E1A2E"),
            textPrimary = Color.WHITE,
            textSecondary = Color.parseColor("#CC88CC"),
            accent = Color.parseColor("#E040FB"),
            accentDark = Color.parseColor("#AA00FF"),
            chipBg = Color.parseColor("#3A1A3A"),
            chipBgActive = Color.parseColor("#E040FB"),
            chipText = Color.parseColor("#CC88CC"),
            chipTextActive = Color.WHITE,
            sliderTrack = Color.parseColor("#3A1A3A"),
            sliderThumb = Color.parseColor("#E040FB"),
            scrollPadBg = Color.parseColor("#2E1A2E"),
            scrollPadThumb = Color.parseColor("#E040FB"),
            scrollPadTrack = Color.parseColor("#3A1A3A"),
            scrollPadArrow = Color.parseColor("#AA55AA"),
            gridBtnBg = "#3A1A3A",
            gridBtnText = "#FFFFFF",
            gridBtnBorder = "#5A2A5A",
            gridBtnActiveBg = "#E040FB"
        ),
        LunaTheme(
            name = "ambar",
            displayNameRes = R.string.theme_amber,
            bgPrimary = Color.parseColor("#1A140D"),
            bgSurface = Color.parseColor("#2E221A"),
            textPrimary = Color.WHITE,
            textSecondary = Color.parseColor("#CCAA88"),
            accent = Color.parseColor("#FFAB00"),
            accentDark = Color.parseColor("#FF6D00"),
            chipBg = Color.parseColor("#3A2A1A"),
            chipBgActive = Color.parseColor("#FFAB00"),
            chipText = Color.parseColor("#CCAA88"),
            chipTextActive = Color.parseColor("#1A140D"),
            sliderTrack = Color.parseColor("#3A2A1A"),
            sliderThumb = Color.parseColor("#FFAB00"),
            scrollPadBg = Color.parseColor("#2E221A"),
            scrollPadThumb = Color.parseColor("#FFAB00"),
            scrollPadTrack = Color.parseColor("#3A2A1A"),
            scrollPadArrow = Color.parseColor("#AA8855"),
            gridBtnBg = "#3A2A1A",
            gridBtnText = "#FFFFFF",
            gridBtnBorder = "#5A3A2A",
            gridBtnActiveBg = "#FFAB00"
        ),
        LunaTheme(
            name = "rojo_gaming",
            displayNameRes = R.string.theme_gaming_red,
            bgPrimary = Color.parseColor("#1A0D0D"),
            bgSurface = Color.parseColor("#2E1A1A"),
            textPrimary = Color.WHITE,
            textSecondary = Color.parseColor("#CC8888"),
            accent = Color.parseColor("#FF1744"),
            accentDark = Color.parseColor("#D50000"),
            chipBg = Color.parseColor("#3A1A1A"),
            chipBgActive = Color.parseColor("#FF1744"),
            chipText = Color.parseColor("#CC8888"),
            chipTextActive = Color.WHITE,
            sliderTrack = Color.parseColor("#3A1A1A"),
            sliderThumb = Color.parseColor("#FF1744"),
            scrollPadBg = Color.parseColor("#2E1A1A"),
            scrollPadThumb = Color.parseColor("#FF1744"),
            scrollPadTrack = Color.parseColor("#3A1A1A"),
            scrollPadArrow = Color.parseColor("#AA5555"),
            gridBtnBg = "#3A1A1A",
            gridBtnText = "#FFFFFF",
            gridBtnBorder = "#5A2A2A",
            gridBtnActiveBg = "#FF1744"
        ),
        LunaTheme(
            name = "purpura",
            displayNameRes = R.string.theme_purple,
            bgPrimary = Color.parseColor("#120D1A"),
            bgSurface = Color.parseColor("#1E1A2E"),
            textPrimary = Color.WHITE,
            textSecondary = Color.parseColor("#9988CC"),
            accent = Color.parseColor("#7C4DFF"),
            accentDark = Color.parseColor("#536DFE"),
            chipBg = Color.parseColor("#2A1A3A"),
            chipBgActive = Color.parseColor("#7C4DFF"),
            chipText = Color.parseColor("#9988CC"),
            chipTextActive = Color.WHITE,
            sliderTrack = Color.parseColor("#2A1A3A"),
            sliderThumb = Color.parseColor("#7C4DFF"),
            scrollPadBg = Color.parseColor("#1E1A2E"),
            scrollPadThumb = Color.parseColor("#7C4DFF"),
            scrollPadTrack = Color.parseColor("#2A1A3A"),
            scrollPadArrow = Color.parseColor("#6655AA"),
            gridBtnBg = "#2A1A3A",
            gridBtnText = "#FFFFFF",
            gridBtnBorder = "#3A2A5A",
            gridBtnActiveBg = "#7C4DFF"
        )
    )

    fun getTheme(name: String): LunaTheme {
        return themes.firstOrNull { it.name == name } ?: themes[0]
    }
}
